<script>
    [
  {
    "id": 1,
    "name": "Brij",
    "phone": "917011767613",
    "avatar": "https://app.dotflo.io/uploads/media/tMVaqzbHxFon70ej1JhYj8BSpv3u4Yyagp79qmn2.png",
    "country_id": 60,
    "company_id": 1,
    "deleted_at": null,
    "created_at": "2023-12-02T04:11:45.000000Z",
    "updated_at": "2023-12-27T04:09:43.000000Z",
    "last_reply_at": "2023-12-19 22:36:43",
    "last_client_reply_at": "2023-12-19 06:15:27",
    "last_support_reply_at": "2023-12-19 22:36:43",
    "last_message": "Hola",
    "is_last_message_by_contact": 0,
    "has_chat": 1,
    "resolved_chat": 0,
    "user_id": null,
    "enabled_ai_bot": 0,
    "email": null,
    "title": null,
    "position": null,
    "website": null,
    "city": null,
    "address": null,
    "gender": null,
    "rating": 0,
    "notes": null,
    "messages": [
      {
        "id": 17,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Hola",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-19T21:36:43.000000Z",
        "updated_at": "2023-12-19T21:36:43.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 16,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-19T21:35:28.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-19 22:35:28",
        "components": "[]",
        "campaign_id": 6,
        "header_audio": ""
      },
      {
        "id": 15,
        "fb_message_id": "wamid.HBgLMTgyOTYwNDQ0MTIVAgASGBQzQTM4N0JFRkRGOEQ1OTk5NzIwMAA=",
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "hello",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 1,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-19T05:15:27.000000Z",
        "updated_at": "2023-12-19T05:15:27.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 14,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-18T02:13:23.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-18 03:13:23",
        "components": "[]",
        "campaign_id": 5,
        "header_audio": ""
      },
      {
        "id": 13,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "hello",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T21:58:14.000000Z",
        "updated_at": "2023-12-17T21:58:14.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 12,
        "fb_message_id": "wamid.HBgLMTgyOTYwNDQ0MTIVAgASGBQzQUJFMDI3NkY0MTQ2Q0ZDNUQ4QwA=",
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "*Hello World*\nWelcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 1,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T21:45:15.000000Z",
        "updated_at": "2023-12-17T21:45:15.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 11,
        "fb_message_id": "wamid.HBgLMTgyOTYwNDQ0MTIVAgASGBQzQTNFNEQ0NTVFRjk3MEMwREUzNgA=",
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Hello",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 1,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T21:32:17.000000Z",
        "updated_at": "2023-12-17T21:32:17.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 10,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "🇦🇮",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:36:48.000000Z",
        "updated_at": "2023-12-17T20:36:48.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 9,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "https://app.dotflo.io/uploads/media/U0FpdlEFjUBiaKZP2u122jCaEBPKt8DVWwS9qnIE.png",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:36:31.000000Z",
        "updated_at": "2023-12-17T20:36:31.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 8,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "https://app.dotflo.io/uploads/media/w9UnrG7I7BO18wsiq2tMD2yXLMIImATxfGAhvXLc.pdf",
        "buttons": "[]",
        "value": "",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:36:22.000000Z",
        "updated_at": "2023-12-17T20:36:22.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 7,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "espero tenga un buen resultado",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:27:23.000000Z",
        "updated_at": "2023-12-17T20:27:23.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 6,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Excelente trabajo",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:26:47.000000Z",
        "updated_at": "2023-12-17T20:26:47.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 5,
        "fb_message_id": "wamid.HBgLMTgyOTYwNDQ0MTIVAgASGBQzQTRENTcxQjlCNDU1QUJBNUJGQgA=",
        "contact_id": 1,
        "company_id": 1,
        "header_text": "",
        "footer_text": "",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Prueba de recibido",
        "error": "",
        "is_campign_messages": 0,
        "is_message_by_contact": 1,
        "message_type": 1,
        "status": 1,
        "created_at": "2023-12-17T20:26:34.000000Z",
        "updated_at": "2023-12-17T20:26:34.000000Z",
        "scchuduled_at": null,
        "components": "",
        "campaign_id": null,
        "header_audio": ""
      },
      {
        "id": 4,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-10T19:16:04.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-10 20:16:04",
        "components": "[]",
        "campaign_id": 4,
        "header_audio": ""
      },
      {
        "id": 3,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-09T03:48:15.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-09 04:48:15",
        "components": "[]",
        "campaign_id": 3,
        "header_audio": ""
      },
      {
        "id": 2,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-02T04:13:05.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-02 05:13:05",
        "components": "[]",
        "campaign_id": 2,
        "header_audio": ""
      },
      {
        "id": 1,
        "fb_message_id": null,
        "contact_id": 1,
        "company_id": 1,
        "header_text": "Hello World",
        "footer_text": "WhatsApp Business Platform sample message",
        "header_image": "",
        "header_video": "",
        "header_location": "",
        "header_document": "",
        "buttons": "[]",
        "value": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
        "error": "",
        "is_campign_messages": 1,
        "is_message_by_contact": 0,
        "message_type": 1,
        "status": 0,
        "created_at": "2023-12-02T04:11:58.000000Z",
        "updated_at": null,
        "scchuduled_at": "2023-12-02 05:11:58",
        "components": "[]",
        "campaign_id": 1,
        "header_audio": ""
      }
    ],
    "country": {
      "id": 60,
      "name": "Dominican Republic",
      "lat": "18.735693",
      "lng": "-70.162651",
      "iso2": "DO",
      "iso3": "DOM",
      "phone_code": "1-809, 1-829, 1-849",
      "timezone": "America/Santo_Domingo",
      "languages": "es-DO",
      "created_at": null,
      "updated_at": null
    }
  }
]
</script>